# Generated by Django 4.1.7 on 2023-03-22 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_multipleimage_delete_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='multipleimage',
            old_name='image',
            new_name='images',
        ),
    ]
